# Generated by Django 5.0.4 on 2024-06-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_moviedate_moviedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='typ',
            field=models.CharField(default='action', max_length=200),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='released',
            field=models.DateField(),
        ),
    ]
